apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux-ks.yaml
  - aso/flux-ks.yaml
  - networking/flux-ks.yaml
  - storage/flux-ks.yaml
  - postgres/flux-ks.yaml
