apiVersion: v1
kind: ConfigMap
metadata:
  name: local-workload-flux-instance
  namespace: default
data:
  flux-instance.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: flux-system
    ---
    apiVersion: fluxcd.controlplane.io/v1
    kind: FluxInstance
    metadata:
      name: flux
      namespace: flux-system
      annotations:
        fluxcd.controlplane.io/reconcileEvery: "1h"
        fluxcd.controlplane.io/reconcileTimeout: "5m"
    spec:
      distribution:
        version: "2.x"
        registry: "ghcr.io/fluxcd"
        artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
      components:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
      cluster:
        type: kubernetes
        size: small
        multitenant: false
        networkPolicy: true
        domain: cluster.local
      sync:
        kind: OCIRepository
        url: oci://krops-registry:5000/krops
        ref: latest
        path: workload/local-host
      kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/insecure
                value: true
            target:
              kind: OCIRepository
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: local-workload-flux-instance
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      fluxcd: enabled
      krops.polarsquad.com/environment: local-host
  strategy: ApplyOnce
  resources:
    - kind: ConfigMap
      name: local-workload-flux-instance
