apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: "v1.14.1"
  deployment:
    containers:
      - name: manager
        args:
          "--feature-gates": "ClusterTopology=true"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: capi-system
spec:
  version: "v1.14.1"
  deployment:
    containers:
      - name: manager
        args:
          "--feature-gates": "ClusterTopology=true"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-system
spec:
  version: "v1.14.1"
  deployment:
    containers:
      - name: manager
        args:
          "--feature-gates": "ClusterTopology=true"
