apiVersion: v1
kind: Secret
metadata:
    name: flux-pull-secret
    namespace: default
type: addons.cluster.x-k8s.io/resource-set
stringData:
    flux-github-pat.yaml: ENC[AES256_GCM,data:2AqfU6YIcPoCcuMMLBxTYxgjAiwbAvT1jMW1XZK1kPYgywDVUPWzKqjq0ZJYrbf0lNmdLL1+CGOm7DRfBNZ08Jx+Hc82w43Y+oAGlkhjZN0/HUacR2U+n0zOpg8aU72zPJqO80a5W6FeE6cYDfiT49Q0zCVshkGAw6PcOPC6Fm7cOakU6OVeZV+s3UylA4niObVPxg3jeAkNFqpjkbn6GcsR8IuAxnYlNBK2GD7thooRO3a++Lyokyjh21KmbFlBiUxivAwrvsOC7T1+EkAPv31a1ON6lesrz2N69Cx7USIZ0svFKUAysrQ=,iv:NYGSADGVw9qVjXildETudLBAqbOhUYX5oHr40bluDMA=,tag:Bg8dqBzVm5pQhEuRoU4eOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd0NpVFAyWmhJQnlOWVlL
            N093a0pVTDNwSGd1Z1JaaVpZTDZnVXM2Q0VBCjhrTXU1UCtCV3lCdWNyS2U3TTI0
            QzU2Yk9nUzZQZER3eTNnaFhLTGdzSEUKLS0tIE40QXl1QkdsSnpLdHR6UnlVMWFv
            NEo2aGJMRkxzZXYrMGxid3VaN3liYzgKiB1taXRCmRf9jI+1Jsgo6wJvrazMLvEK
            0Lg09YFT4L3P6i9cao8ieedL/JWL42ukdilBknnGgGF2ExCsCkonow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T07:41:15Z"
    mac: ENC[AES256_GCM,data:wKRLkjLFjBn+qSkItquZqHNYLl9qxemws3423Dei+9WRTuwosL+yOHpCDoCDNz8mXIMgN+yr/DyzG1qr8kPf+BYphyWzQuf6wsixbfi8OksdARURHtf+2bP7d6Xr7Hh6v733YSZY2yy7sGQCxNG0CI2Jo3UQT2PrwWGqItKNlJA=,iv:9n8KoaVC8LH+IPlUrROvMhMhJXhxmksx60c/EiZnnyU=,tag:6kJYnTFOuL3uOuOCVe93qA==,type:str]
    version: 3.13.2
