apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - capi-operator
  - aws-identity
  - aws-clusters-resources
  - ack-controllers
  - workload-resources
  - aws-global-iam
  - konflate
