apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: capa-system
type: Opaque
stringData:
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:/Lpl6m5Kx+t9wQZxS3UdDgUJbc2VnCXLe9GnCRLvN8GTCuMC0EUZwaFhE4mkplSDo6PVii9zFl/5ZGv9ddrXOBj2aIdUiMNNgMfiA33nb8IMYHIs2ptWrfNMzNliV4D4Oui6ujBxmK32iAHReZ7RM6fUsX5Rraxo99Dr8UU4b2ctcuARs5vcbPm8ds+cPerl3CTLjDya2duwXZEKeiPTiJTQe1bWorNXdlLOsnw+ALOCZujZcs+15g==,iv:RbzDMXyi0RcJpBR+WuEbfpHYLAWiS+iDGHZ49tKr27s=,tag:qLkMjgefzd3hDNRczAOq5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VEZlZjVXSGx3OFRuZlR0
            UU9yUCtMc2Irc013blJBQnVoMGxBQ2FwRGlFCkE2SjJjUEdQeHd2ekF5bmVuYmZk
            QTNQSnZQMWZzZFBMNStGZHJKcE15U1UKLS0tIFplOFBiOC9aZGdobjZVNjhzbGM5
            dTNiM3RvcUJtdlQrY1NOOVJVaEVrbE0KceCcfOlNp4jDKLUqoCvEPHnVhWmfwQdX
            gTwMOLX+13gP4mB6mbecFOEGncFMoGuR6zapaYpAS1w9PYY1e9Toqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T17:19:10Z"
    mac: ENC[AES256_GCM,data:pOaBHvPMECcLFYLWcetjsP8sJFvMTxBXUktv8Z82ML3ftKndM26SUv6XuxqYn6M5bErMQtktnNY04J9+uh+juOeM3ASyVO6pEiQwDblC38hdPXJjf91iwcBEBiFaop6VmHKcCqLiUoZMIxz+FkUNvNaXOyx/5+//8FjEmSy7IT8=,iv:pHS+Ielh5AyR7nkGYrcphxe0Z8anVx9uqNj9oEeBvII=,tag:xNu2XH+SHY08RgXch5M2zg==,type:str]
    version: 3.13.3
