apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        kind: HelmRepository
        name: capi-operator
      # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/cluster-api-operator depName=cluster-api-operator
      version: "0.29.0"
  values:
    manager: {}
