apiVersion: v1
kind: Secret
metadata:
    name: aso-credentials
    namespace: default
type: Opaque
stringData:
    AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:vHW28OBQfEGQGEM3rxImZt4NzBMZlr/3U6882xEud7pE38CM,iv:yQBIaLPtBKZi6EVrxaMRD6bY7WquBzzNVzqoS8QGiBY=,tag:t9VlPotAUNv1g6iOusyADg==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:SZ8XGJzBJfbRoiuBI4ue6IimJHL5mycYEQ2M/QhtyGO+Avg2,iv:E/k4Vo47SEf7J5HC4YLriGjELvRjUCEdJSAstpAKK8Y=,tag:+Iu2tXmHjmbbSaOLPg00Qg==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:yDAqgNA1zjZzurjdMNfHkI++aHm7dxfNtt6Txp5qvynk5rvM,iv:87b+8BdQ8GIofnelsi7pKuiO33HosEP3AVPytf3uZsM=,tag:KR8vIQBIjUmZyH8/xD0mpw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:YKy4TCsHn79B+w==,iv:3OW45YJU5LCvl8rG/U4hT3uQ8yNHSVBlpidBPGAIRvE=,tag:bljqUcPgblCDM9YNc8dDMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Tm11alNUb1ZRUkRmeTBj
            ckZOM1ZaWXphNzMwVkdjZTlreEtmOUphcFY4Ck5wdW9xcGJ1TVJKOHlWazlPWmVV
            ZVFacU9PZktRZlNtMnVjRTJJZk5iMTgKLS0tIEdSNkVUa2I1WDNjc05aU0pCU2s2
            M0xhREgvdStuQy9qR1puU3B5UUNxSUEK/Kl4ZYRuUgJnu6FB6W9ovWsFvxzRoQvI
            3VCH7bcA4iDUks+ySmB18KQIZT5WE7etSdDfrCU/yr9uoaxIOgGxJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T06:40:36Z"
    mac: ENC[AES256_GCM,data:qcPew191bIjXi9lmZUsWhQlemBBxufcaOfxatBqrxNfRfEx3UU9jcD+9qPsnbwublejIPo/R5o+bSg1AqGbuUgNB9s8gD6WOmdVx1NX6Yj2bMQmA2eeeqIUIci2nh0Y7b8puM3npDvLGoVFLOKk/3GN/0RQ7/0JwOAZAayaw4ko=,iv:qCTckgv3egk3uwUaz+xrsX6D2TeTUywOV6ud621iDdo=,tag:2pxK5yaPs8dTMANrXPIFtg==,type:str]
    version: 3.13.3
