apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcc-operator
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kcc-operator
    namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  targetNamespace: configconnector-operator-system
