apiVersion: v1
kind: Secret
metadata:
    name: flux-github-pat
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xjRc,iv:w4meOnV+nvBA/MhzOIzkGUWC1skEnOPwGzd/tm4L9h4=,tag:wHc99UyVb8GP3vx5UAsFyA==,type:str]
    password: ENC[AES256_GCM,data:jynaMghFGbajrg5hJlaINpllgtPjMxC1KIcGACV2bQhrFgRCEDqWvo7Wa3WIUa9fA+LB0VH86o1VeAj3T8vDHHVWGV/yXw1t8NPRoVJN/v+pRdpYjpR/+UCjNP9/,iv:UaJG0HiRUDpTY0GX9N04zLczQDhc1Ubmhd6OswTwIlA=,tag:cWgLcYLFNH7NJQM9sxD8eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWVNNak5xa3diZjhYMHhN
            a0gyVG5QbmRoUnhFNXN0eFpSWldCaWFweUdvCjcwUy9TcFd2bzRoNkhXUTZkWm9P
            aUNRTnBXUm1uVVhKdkFVdGlJaVRMYTgKLS0tIDJBclZQdHhmcTlkbER3c1F5MStx
            QS9RWXFEaUdCTnl6cHZvS0V3bVZvQ2cKY0deuF8bde6odKJ2mqkA2r2VsGQBZlWZ
            So7G3/SsRCmIospInTDmfuTPyawsaSDZwdOnyTLLpbEuO8fI9LagtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T18:23:23Z"
    mac: ENC[AES256_GCM,data:+taJR02EZsTbK3rTTHEZYAplYcPSK3NjHW97G90y2aF/Ua/yNxq/mUww9NuUcyyeQR3Un44WMVdN5S75TPxM8p7oman+taIZSURcHa2/ZU76hBvDfyG65oExpnCq6+TUIJZMRxSNh4/CeODo5jSrsTqgHfUQOerZTk98RsikCrY=,iv:/5DDdTtccujH+cu2bFdsJWjjC8WlA4G4+Y9w7LyoYTo=,tag:I0QOHjGrvE9A7O5soG3pdw==,type:str]
    version: 3.13.3
